### ISSUE TITLE
[Bug] uninstall the extension broke xdg-open

### ISSUE THREAD

**Issue by x0rld** [blipk/bowser-gnome#11]
**To Reproduce**
1 install it
2 uninstall it
3  xdg-open doesn't work 

**Expected behavior**
xdg-open works
**Screenshots**
![image](https://user-images.githubusercontent.com/45242856/106801300-dff26e00-6661-11eb-8262-a78f44e9dac2.png)

 - Gnome-Shell Version: GNOME Shell 3.38.3

**Comment by blipk** [comment]
Hi.

This is because there is no routine in the gnome extension system that can be run when an extension is uninstalled, that I'm aware of.

There is the disable() routine but that is run on when the extensions is disabled as well as uninstalled, and this can often happen automatically with gnome-shell crashes and can cause quite a bit of lag, also in a previous version it was possible to set up your rules then disable the extension via gnome-shell but keeping it as the default browser and they would still work (this can still work, needs to be fixed)

To fix your issue:
Before uninstalling please toggle the 'Bowser Enabled' option, this will turn off the default browser assignment.
Alternatively you can do this in the Gnome Settings 'default applications' area.
Can also be done via command line with `xdg-settings set default-web-browser firefox.desktop`

**Comment by x0rld** [comment]
ok thank you
