### ISSUE TITLE
Gnome shortcut opens widget popup window instead of the default binary

### ISSUE THREAD

**Issue by CiottiGiorgio** [blipk/bowser-gnome#17]
Pretty much title. In my opinion the shortcut for Gnome (default is Super+B) should open up the default browser and not Bowser popup.

**Comment by blipk** [comment]
Hi @CiottiGiorgio 

Makes sense that that should be default behaviour, didn't realise there was a shortcut to open web browser.

Bowser actually works by acting as the default browser and passing on to other browsers, however if no URL was provided it was intended to open the popup menu, this was to be able to open the settings from the extensions settings but that was removed.

In any case, I've changed it so that so if no URL is passed it will just open a new window to your default browser (I tried to get it to open same window but Firefox at least won't do that if you don't pass a URL - you can maybe get around this with a custom .desktop file and some flags)

You can use the latest zip on git or wait for the extensions site to approve the updates.

**Comment by CiottiGiorgio** [comment]
That's awesome! Thank you!
